### ISSUE TITLE
Error: Rule failed to generate the following targets src/stdlib_shims.a

### ISSUE THREAD

**Issue by shakthimaan** [ocaml/stdlib-shims#16]
I am trying to build stdlib-shims for OCaml 4.12.0 (https://github.com/ocaml/ocaml/archive/trunk.tar.gz) with dune.2.6.0, and I get the following error:
```
File "_build/.dune/default/src/dune", line 2, characters 0-75:
2 | (library
3 |  (wrapped false)
4 |  (name stdlib_shims)
5 |  (public_name stdlib-shims))
Error: Rule failed to generate the following targets:
- src/stdlib_shims.a
```
What could be the reason?

**Comment by dra27** [comment]
You need https://github.com/ocaml/dune/pull/3576, which I just merged to dune master.

As a (very) small aside, OCaml 4.12.0 isn't released, so we prefer to say "trunk OCaml" (for the branch) as it's a development version
