### ISSUE TITLE
opam switches 4.12.0 and up fail to produce `stdlib_shims.a`

### ISSUE THREAD

**Issue by mobileink** [ocaml/stdlib-shims#20]
On my installation it looks like versions 4.12 and up are failing to produce `stdlib-shims/stdlib_shims.a`.  They do produce `stdlib-shims/stdlib_shims.cmxa`.  To reproduce install the switch then install `ounit2`.  Is this a bug?

**Comment by dra27** [comment]
That's correct - `stdlib_shims.cmxa` is empty. Since 4.12, OCaml no longer emits C libraries in this case (see https://github.com/ocaml/ocaml/pull/9011).
